rm packages/reactor-a-demo16/package-lock.json
rm packages/extjs-to-react-converter/package-lock.json
rm packages/extjs-webpack-plugin/package-lock.json
rm packages/generator-ext-react/package-lock.json
rm packages/generator-sencha-generate/package-lock.json
rm packages/reactor-a-demo16/package-lock.json
rm packages/reactor-babel-plugin/package-lock.json
rm packages/reactor-boilerplate15/package-lock.json
rm packages/reactor-boilerplate16/package-lock.json
rm packages/reactor-classic-boilerplate15/package-lock.json
rm packages/reactor-classic-boilerplate16/package-lock.json
rm packages/reactor-conference-app15/package-lock.json
rm packages/reactor-conference-app16/package-lock.json
rm packages/reactor-kitchensink15/package-lock.json
rm packages/reactor-kitchensink16/package-lock.json
rm packages/reactor-modern-boilerplate15/package-lock.json
rm packages/reactor-modern-boilerplate16/package-lock.json
rm packages/reactor-rest-example15/package-lock.json
rm packages/reactor-rest-example16/package-lock.json
rm packages/reactor-tests/package-lock.json
rm packages/reactor-tests15/package-lock.json
rm packages/reactor-tests16/package-lock.json
rm packages/reactor-typescript-boilerplate15/package-lock.json
rm packages/reactor-typescript-boilerplate16/package-lock.json
rm packages/reactor-webpack-plugin/package-lock.json
rm packages/reactor15/package-lock.json
rm packages/reactor16/package-lock.json
rm packages/sencha-build/package-lock.json