rm ext-build/node_modules
rm ext-build/package-lock.json
rm ext-build-generate-app/package-lock.json
rm ext-gen/package-lock.json
rm ext-webpack-plugin/package-lock.json
rm extjs-to-react-converter/package-lock.json
rm generator-ext-react/package-lock.json
rm reactor-a-demo16/package-lock.json
rm reactor-babel-plugin/package-lock.json
rm reactor-boilerplate15/package-lock.json
rm reactor-boilerplate16/package-lock.json
rm reactor-classic-boilerplate15/package-lock.json
rm reactor-classic-boilerplate16/package-lock.json
rm reactor-conference-app15/package-lock.json
rm reactor-conference-app16/package-lock.json
rm reactor-kitchensink15/package-lock.json
rm reactor-kitchensink16/package-lock.json
rm reactor-modern-boilerplate15/package-lock.json
rm reactor-modern-boilerplate16/package-lock.json
rm reactor-rest-example15/package-lock.json
rm reactor-rest-example16/package-lock.json
rm reactor-tests/package-lock.json
rm reactor-tests15/package-lock.json
rm reactor-tests16/package-lock.json
rm reactor-typescript-boilerplate15/package-lock.json
rm reactor-typescript-boilerplate16/package-lock.json
rm reactor-webpack-plugin/package-lock.json
rm reactor15/package-lock.json
rm reactor16/package-lock.json
