rm -r ext-build/node_modules
rm -r ext-build-generate-app/node_modules
rm -r ext-gen/node_modules
rm -r ext-webpack-plugin/node_modules
rm -r extjs-to-react-converter/node_modules
rm -r generator-ext-react/node_modules
rm -r reactor-a-demo16/node_modules
rm -r reactor-babel-plugin/node_modules
rm -r reactor-boilerplate15/node_modules
rm -r reactor-boilerplate16/node_modules
rm -r reactor-classic-boilerplate15/node_modules
rm -r reactor-classic-boilerplate16/node_modules
rm -r reactor-conference-app15/node_modules
rm -r reactor-conference-app16/node_modules
rm -r reactor-kitchensink15/node_modules
rm -r reactor-kitchensink16/node_modules
rm -r reactor-modern-boilerplate15/node_modules
rm -r reactor-modern-boilerplate16/node_modules
rm -r reactor-rest-example15/node_modules
rm -r reactor-rest-example16/node_modules
rm -r reactor-tests/node_modules
rm -r reactor-tests15/node_modules
rm -r reactor-tests16/node_modules
rm -r reactor-typescript-boilerplate15/node_modules
rm -r reactor-typescript-boilerplate16/node_modules
rm -r reactor-webpack-plugin/node_modules
rm -r reactor15/node_modules
rm -r reactor16/node_modules
